#!/bin/bash

CLASSPATH='.:src/:lib/:lib/sigar.jar:lib/mysql-connector-java.jar:/usr/share/tomcat/lib/tomcat-servlet-3.0-api.jar'

javac -cp $CLASSPATH src/perfmon/util/*.java
javac -cp $CLASSPATH src/perfmon/agent/util/*.java
javac -cp $CLASSPATH src/perfmon/database/*.java
javac -cp $CLASSPATH src/perfmon/agent/base/*.java
javac -cp $CLASSPATH src/perfmon/agent/*.java
javac -cp $CLASSPATH src/*.java

mkdir -p \
	src/perfmon/dashboard/WEB-INF/classes/perfmon/ \
	src/perfmon/dashboard/WEB-INF/classes/perfmon/util/ \
	src/perfmon/dashboard/WEB-INF/classes/perfmon/database/ 
cp -Rv src/perfmon/util/*.class src/perfmon/dashboard/WEB-INF/classes/perfmon/util/
cp -Rv src/perfmon/database/*.class src/perfmon/dashboard/WEB-INF/classes/perfmon/database/

javac -cp $CLASSPATH -d src/perfmon/dashboard/WEB-INF/classes/ src/perfmon/dashboard/Dashboard.java
